### PR TITLE
Add photo and details to AboutUs page. 

### PR DESCRIPTION
**Pull request by sueann-chua**
Responsibilities to be filled in.

### CODE REVIEW

**Comment by seaweediman** [comment]
Can you add your portfolio as team/sueann-chua.md first?

**Comment by sueann-chua** [comment]
> Can you add your portfolio as team/sueann-chua.md first?

It was added in line 36

**Comment by seaweediman** [comment]
> > Can you add your portfolio as team/sueann-chua.md first?
> 
> It was added in line 36

Sorry, I meant that sueann-chua.md doesn't exist. So when you click on [portfolio], an error occurs.

**Comment by sueann-chua** [comment]
> > > Can you add your portfolio as team/sueann-chua.md first?
> > 
> > 
> > It was added in line 36
> 
> Sorry, I meant that sueann-chua.md doesn't exist. So when you click on [portfolio], an error occurs.

oh I see, I have made the relevant changes

**Review by seaweediman — APPROVED** [review]
LGTM

**Pull request merged**
